# Generated by Django 4.1.3 on 2022-11-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_factura',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_factura',
        ),
    ]
